version: "3.8"

services:
  # Service pour la base de données MySQL
  db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql_station_ski
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  # Service pour l'application Spring Boot
  app:
    image: mahmoudgh01/gestion-station-ski:1.0
    container_name: spring_station_ski
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url"  : "jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true",
              "spring.datasource.username" : "root",
              "spring.datasource.password" : "root",
              "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
              "spring.jpa.hibernate.ddl-auto" : "update"
            }'
    stdin_open: true
    tty: true
    restart: on-failure
    ports:
      - "8089:8089"
    networks:
      - backend-network


volumes:
  mysql_data:

networks:
  backend-network:
