static_configs:
  - targets: ["localhost:9090"]
  - job_name: jenkins
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['192.168.33.10:8082']
        labels:
          group: 'production'

  - job_name: 'mysql'
    static_configs:
      - targets: ['192.168.33.10:9104']